name: gradle CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE-HEADER'
      - '.gitignore'
      - '.editorconfig'
      - 'CHANGELOG.md'
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with gradle

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build latest VCS version
        run: ./gradlew buildAndCollect --stacktrace

      - uses: actions/upload-artifact@v6
        with:
          path: build/finalJars/*.jar
